export const languages = {
  en: {
    students: "Students",
    teachers: "Teachers",
    courses: "Courses",
    schedule: "Schedule",
    classrooms: "Classrooms",
    addStudent: "Add New Student",
    fullName: "Full Name",
    studentId: "Student ID",
    delete: "Delete",
    home: "Welcome to the school management module.",
    export: "Export Data",
    import: "Import Data",
    title: "School Management System",
    add: "Add",
    addTeacher: "Add New Teacher",
    subject: "Subject exp:Math",
    subjectTable: "Subject",
    addCourse: "Add New Course",
    courseName: "Course Name",
    courseCode: "Course Code",
    code: "Code",
    selectDay: "Select Day",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    selectCourse: "Select Course",
    selectTeacher: "Select Teacher",
    selectClassroom: "Select Classroom",
    day: "Day",
    time: "Time",
    course: "Course",
    teacher: "Teacher",
    classroom: "Classroom",
    courseSelectFieldWarning: "Course selection field not found.",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    addToSchedule: "Add to Schedule",
    addClassroom: "Add New Classroom",
    classroomName: "Classroom Name",
    capacity: "Capacity",
    classroom: "Classroom",
    login: "Login",
    dashboard: "Dashboard",
    welcome: "Welcome",
    dashboardDescription:
      "This page is a summary of information about school management.",
    settings: "Settings",
    selectTheme: "Select Theme",
    light: "Light",
    dark: "Dark",
    selectLanguage: "Select Language",
    exportData: "Export Data",
    importData: "Import Data",
    clearData: "Clear All Data",
    confirmClear: "Are you sure you want to delete all data?",
  },
  tr: {
    students: "Öğrenciler",
    teachers: "Öğretmenler",
    courses: "Dersler",
    schedule: "Ders Programı",
    classrooms: "Sınıflar",
    addStudent: "Yeni Öğrenci Ekle",
    fullName: "Ad Soyad",
    studentId: "Öğrenci No",
    delete: "Sil",
    home: "Okul yönetim modülüne hoş geldiniz.",
    export: "Verileri Dışa Aktar",
    import: "Verileri İçe Aktar",
    title: "Okul Yönetim Sistemi",
    add: "Ekle",
    addTeacher: "Yeni Öğretmen Ekle",
    subject: "Branş örn:Matematik",
    subjectTable: "Branş",
    addCourse: "Yeni Ders Ekle",
    courseName: "Ders Adı",
    courseCode: "Ders Kodu",
    code: "Kod",
    selectDay: "Gün",
    monday: "Pazartesi",
    tuesday: "Salı",
    wednesday: "Çarşamba",
    thursday: "Perşembe",
    friday: "Cuma",
    selectCourse: "Ders Seç",
    selectTeacher: "Öğretmen Seç",
    selectClassroom: "Sınıf Seç",
    day: "Gün",
    time: "Saat",
    course: "Ders",
    teacher: "Öğretmen",
    classroom: "Sınıf",
    courseSelectFieldWarning: "Ders seçme alanı bulunamadı.",
    lightMode: "Açık Mod",
    darkMode: "Koyu Mod",
    addToSchedule: "Programa Ekle",
    addClassroom: "Yeni Sınıf Ekle",
    classroomName: "Sınıf Adı",
    capacity: "Kapasite",
    classroom: "Sınıf",
    login: "Giriş",
    dashboard: "Yönetim Paneli",
    welcome: "Hoşgeldin",
    dashboardDescription:
      "Bu sayfa okul yönetimi ile ilgili bilgilerin özet olarak gösterildiği sayfadır.",
    settings: "Ayarlar",
    selectTheme: "Tema Seç",
    light: "Açık",
    dark: "Koyu",
    selectLanguage: "Dil Seç",
    exportData: "Verileri Dışa Aktar",
    importData: "Verileri İçe Aktar",
    clearData: "Tüm Verileri Temizle",
    confirmClear: "Tüm verileri silmek istediğinizden emin misiniz?",
  },
};
